apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: team-a
spec:
  releaseName: hello-arc
  chart:
    git: https://github.com/likamrat/hello_arc
    ref: master
    path: charts/hello-arc
  values:
    serviceName: hello-arc

