apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: team-a
spec:
  releaseName: nginx-ingress
  chart:
    git: https://github.com/likamrat/hello_arc
    ref: master
    path: charts/nginx-ingress
  values:
    serviceName: nginx-ingress

